### ISSUE TITLE
Not working with php8.*

### ISSUE THREAD

**Issue by wrcgam** [mkrohn/laravel-odbc-informix#1]
I have installed as mentioned in the readme, but I am getting a fatal error of no support for pdo functions.

The error is the following:
Declaration of Mkrohn\Odbc\ODBCPdoStatement::fetchAll($how = null, $class_name = null, $ctor_args = null) must be compatible with PDOStatement::fetchAll(int $mode = PDO::FETCH_DEFAULT, mixed ...$args )

Can you help me fix this? I'm running PHP 8.0.*

**Comment by mkrohn** [comment]
Ho wrcgam, don't worry, it is compatible, those parameters are not used anyway, because in the end it calls internal php function  `odbc_fetch_array(resource $result, int $rownumber = ?): array`

**Comment by unifusions** [comment]
this was working, when the function name changed to this

`public function fetchAll(int $how = PDO::FETCH_BOTH,mixed  ...$ctor_args): array|false`

**Comment by wrcgam** [comment]
And what should I do to solve the error ?

**Comment by wrcgam** [comment]
And what should I do to solve the error ?
